name: Publish EasyPersistence.EFCore to NuGet

on:
  workflow_dispatch:

jobs:
  build-sign-pack-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
         
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies EFCore
        run: dotnet restore src/EFCore/EFCore.csproj

      - name: Restore dependencies EfCoreSqlClr
        run: dotnet restore src/EfCoreSqlClr/EfCoreSqlClr.csproj

      - name: Build EfCoreSqlClr to make sure it works fine
        run: dotnet build src/EfCoreSqlClr/EfCoreSqlClr.csproj --configuration Release --no-restore
      
      - name: Build EFCore project (Release, signed)
        run: dotnet build src/EFCore/EFCore.csproj --configuration Release --no-restore

      - name: Pack EFCore project (includes EfCoreSqlClr)
        run: dotnet pack src/EFCore/EFCore.csproj --configuration Release --no-build --output ./artifacts -p:SuppressDependenciesWhenPacking=true

      - name: Publish package to NuGet
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    
      - name: Publish symbols package to NuGet
        run: dotnet nuget push artifacts/*.snupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate

